version: '3.4'

services:
  cidotnet.angularcalc:
    depends_on:
      - "cidotnet.angular.app"
    image: ${DOCKER_REGISTRY-}cidotnetangularcalc
    build:
      context: .
      dockerfile: CiDotNet.AngularCalc/Dockerfile
      args:
        - skip_client_build=true
  cidotnet.angular.app:
    image: ${DOCKER_REGISTRY-}cidotnetangularapp
    build:
      context: .
      dockerfile: CiDotNet.AngularCalc/ClientApp/Dockerfile
    ports:
      - "4200:4200" 
      - "49153:49153"
    volumes:
      - ./CiDotNet.AngularCalc/ClientApp:/app
