version: '3.4'

services:
  cidotnet.angularcalc:
    depends_on:
      - "cidotnet.angular.app"
    image: rpetlakcfpl/angular-calc-api
    ports:
      - "4250:80" 
  cidotnet.angular.app:
    image: rpetlakcfpl/angular-calc-app
    ports:
      - "4200:80" 

